export const metadata = {
  title: "Ad Manager",
  description: "Generated by GP",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-white ">
        <div className="rounded-lg  ">

          {children}
        </div>

      </body>
    </html>
  );
}
