import Image from "next/image";
export const metadata = {
  title: "Ad Manager",
  description: "Generated by GP",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-white ">
        <div className="rounded-lg  ">
          <Image
            className="logotop mx-auto mb-6"
            src="/logo.png"
            alt="Creative Manager"
            width={201}
            height={37}
            priority
          />
          {children}
        </div>

      </body>
    </html>
  );
}
